resources:
  reference_table:
    read:
      method: get
      path: /api/v2/reference-tables/tables/{id}
    create:
      method: post
      path: /api/v2/reference-tables/tables
    update:
      method: patch
      path: /api/v2/reference-tables/tables/{id}
    delete:
      method: delete
      path: /api/v2/reference-tables/tables/{id}

datasources:
  reference_table:
    singular: /api/v2/reference-tables/tables/{id}
    plural: /api/v2/reference-tables/tables
  reference_table_rows:
    singular: /api/v2/reference-tables/tables/{id}/rows
    plural: /api/v2/reference-tables/tables/{id}/rows