resources:
  datastore:
    read:
      method: get
      path: /api/v2/actions-datastores/{datastore_id}
    create:
      method: post
      path: /api/v2/actions-datastores
    update:
      method: patch
      path: /api/v2/actions-datastores/{datastore_id}
    delete:
      method: delete
      path: /api/v2/actions-datastores/{datastore_id}

datasources:
  datastore:
    singular: /api/v2/actions-datastores/{datastore_id}
    plural: /api/v2/actions-datastores
